### PR TITLE
Added display name and lore functionality to the ItemMeta.

### PR DESCRIPTION
**Pull request by Serializator**
Added display name and lore functionality to the ItemMeta.

### CODE REVIEW

**Comment by nickrobson** [comment]
Perhaps they would be better as

```java
Optional<String> getDisplayName();
Optional<List<String>> getLore():
```

As this means the `hasXXXXX` functions aren't needed.

**Comment by nickrobson** [comment]
:+1:

**Comment by TheLightMC** [comment]
Wouldn't it be better to have an empty list being returned instead of an Optional? @nickrobson Not sure if it really matters but imo it seems more fluid. Mind sharing your reasoning on the Optional?

**Comment by Fireflies** [comment]
An empty `Optional` indicates that the property is absent, nothing more to be said.

**Comment by TheLightMC** [comment]
Fair enough

**Comment by Serializator** [comment]
There were some problems with my fork and I had to reset my branches, I submitted a new PR (#67) with the same changes.

**Pull request closed without merging**
