### PR TITLE
Changed 'headYaw' to 'bodyYaw'.

### PR DESCRIPTION
**Pull request by Serializator**

### CODE REVIEW

**Comment by j0ach1mmall3** [comment]
y?

**Comment by Serializator** [comment]
What do you mean with `y?`?

**Comment by j0ach1mmall3** [comment]
why? why change it?

**Comment by Serializator** [comment]
Because the variable doesn't represent the yaw from the head but from the body.

**Comment by j0ach1mmall3** [comment]
ok

**Pull request merged**
