### PR TITLE
Improved the performance of Material#getMaterial().

### PR DESCRIPTION
**Pull request by Serializator**

### CODE REVIEW

**Comment by Fireflies** [comment]
Travis failed and thus we cannot accept this.

/s

**Comment by WeeSkilz** [comment]
:+1:

**Comment by DarkSeraphim** [comment]
Calling `values()` inside a double brace init will call `Map#values()` rather than `Enum#values()`, so you're adding all values of an initially empty Map to itself :stuck_out_tongue:

**Comment by DarkSeraphim** [comment]
Been open long enough, changes are good, all tests and checks pass, and I see no reason to keep it open any longer.

**Pull request merged**
